// The MIT License (MIT)
//
// Copyright (c) 2016 Luke Zhao <me@lkzhao.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

import UIKit

struct City {
    var name: String //国名
    var image: UIImage  //イメージ
    var shortDescription: String  //大陸名
    var description1: String  //首都
    var language: String  //言語
    var money: String  //通過
    var color:String  //国旗色

  static var cities = [
    City(name: "America",
         image: #imageLiteral(resourceName: "America"),
         shortDescription: "North American",
         description1: "Washington, D.C.",
         language: "English,Spanish ...etc",
         money: "American dollar",
         color: "赤: 母国であるイギリス\n白: イギリスからの独立"
    ),
    City(name: "Argentine",
         image: #imageLiteral(resourceName: "Argentine"),
         shortDescription: "South America",
         description1: "Buenos Aires",
         language: "Spanish",
         money: "peso",
         color: "太陽:スペインからの独立のシンボル「五月の太陽」\n青：空と海、正義、真実、友情\n白：平和"
    ),
    City(name: "Australia",
         image: #imageLiteral(resourceName: "Australia"),
         shortDescription: "Eurasia",
         description1: "Canberra",
         language: "English",
         money: "dollar",
         color: "イギリスマーク：イギリス連邦の一員"
    ),
    City(name: "Austria",
         image: #imageLiteral(resourceName: "Austria"),
         shortDescription: "Europe",
         description1: "Vienna",
         language: "German",
         money: "Euro",
         color: "十字軍遠征でレオポルド公の白軍服が\n締めていたベルトの部分を除いて\n敵の返り血で赤く染まったという故事による"
    ),
    City(name: "Belgium",
         image: #imageLiteral(resourceName: "Belgium"),
         shortDescription: "Europe",
         description1: "Brussels",
         language: "Dutch、French、German",
         money: "Euro",
         color: "ブラバンド公家紋ゆかりの「黒地に赤い舌を出した黄色いライオン」に由来"
    ),
    City(name: "Bolivia",
         image: #imageLiteral(resourceName: "Bolivia"),
         shortDescription: "South America",
         description1: "Sucre",
         language: "Aymara、Quechua、Spanish",
         money: "boliviano",
         color: "赤：独立闘争で流された血\n黄：豊かな鉱物資源\n緑：森林資源"
    ),
    City(name: "Brazil",
         image: #imageLiteral(resourceName: "Brazil"),
         shortDescription: "South America",
         description1: "Brasilia",
         language: "Portuguese",
         money: "real",
         color: "帯の文字…ポルトガル語で「秩序と発展」\n黄：鉱物資源\n緑：森林資源"
    ),
    City(name: "Canada",
         image: #imageLiteral(resourceName: "Canada"),
         shortDescription: "North American",
         description1: "Ottawa",
         language: "English,French..etc",
         money: "dollar",
         color: "両側の赤：太平洋と大西洋"
    ),
    City(name: "Chile",
         image: #imageLiteral(resourceName: "Chile"),
         shortDescription: "South America",
         description1: "Santiago",
         language: "Spanish",
         money: "Chilean peso",
         color: "星：国家統一、名誉、進歩\n青：空と海\n白：アンデスの清らかな雪\n赤：独立闘争で流された血"
    ),
    City(name: "China",
         image: #imageLiteral(resourceName: "China"),
         shortDescription: "Asia",
         description1: "Beijing",
         language: "Chinese",
         money: "Chinese Yuan",
         color: "紅色：革命、共産主義革命"
    ),
    City(name: "Croatia",
         image: #imageLiteral(resourceName: "Croatia"),
         shortDescription: "Europe",
         description1: "Zagreb",
         language: "Croat",
         money: "Kuna",
         color: "赤：尊い血の犠牲\n白：まばゆく輝く光明\n青：澄みわたる空"
    ),
    City(name: "Czech",
         image: #imageLiteral(resourceName: "Czech"),
         shortDescription: "Europe",
         description1: "Prague",
         language: "Czech",
         money: "Czech koruna",
         color: "青：空\n白：清潔\n赤：自由のために流された血"
    ),
    City(name: "Denmark",
         image: #imageLiteral(resourceName: "Denmark"),
         shortDescription: "Europe",
         description1: "Copenhagen",
         language: "Danish",
         money: "Danish krone",
         color: "赤：祖国愛\n十字マーク：キリスト教への信仰"
    ),
    City(name: "Egypt",
         image: #imageLiteral(resourceName: "Egypt"),
         shortDescription: "Africa",
         description1: "Cairo",
         language: "Arabic",
         money: "pound",
         color: "赤：革命、犠牲者の血\n白：希望、平和\n黒：過去の抑圧"
    ),
    City(name: "Finland",
         image: #imageLiteral(resourceName: "Finland"),
         shortDescription: "Europe",
         description1: "Helsinki",
         language: "Finnish",
         money: "Euro",
         color: "青：湖沼\n白：雪"
    ),
    City(name: "French",
         image: #imageLiteral(resourceName: "French"),
         shortDescription: "Europe",
         description1: "Paris",
         language: "French",
         money: "Euro",
         color: "青：自由\n白：平等\n赤：博愛"
    ),
    City(name: "Germany",
         image: #imageLiteral(resourceName: "Germany"),
         shortDescription: "Europe",
         description1: "Berlin",
         language: "German",
         money: "Euro",
         color: "黒：勤勉\n赤：情熱\nｵﾚﾝｼﾞ：名誉"
    ),
    City(name: "Greece",
         image: #imageLiteral(resourceName: "Greece"),
         shortDescription: "Europe",
         description1: "Athens",
         language: "Greek",
         money: "Euro",
         color: "十字マーク：\n青：青空、エーゲ海\n白：純潔、平和\nストライプ：ギリシャ神話のゼウスの9人の娘を表す"
    ),
    City(name: "Hungary",
         image: #imageLiteral(resourceName: "Hungary"),
         shortDescription: "Europe",
         description1: "Budapest",
         language: "Hungarian",
         money: "forint",
         color: "赤：尊い血の犠牲\n白：平和\n緑：希望"
    ),
    City(name: "India",
         image: #imageLiteral(resourceName: "India"),
         shortDescription: "Asia",
         description1: "Delhi",
         language: "Hindi",
         money: "Rupee",
         color: "オレンジ：ヒンズー教\n白：ヒンズー教とイスラム教の和解と調和\n緑：イスラム教"
    ),
    City(name: "Indonesia",
         image: #imageLiteral(resourceName: "Poland"),
         shortDescription: "Asia",
         description1: "Jakarta",
         language: "Indonesian",
         money: "rupiah",
         color: "赤: 自由と勇気\n白: 正義と純潔"
    ),
    City(name: "iran",
         image: #imageLiteral(resourceName: "iran"),
         shortDescription: "Asia",
         description1: "Tehran",
         language: "Persian",
         money: "Iranian rial",
         color: "緑：イスラム教\n白：平和と友情\n赤：共和国憲法発布、勇気"
    ),
    City(name: "italia",
         image: #imageLiteral(resourceName: "italia"),
         shortDescription: "Europe",
         description1: "Rome",
         language: "Italian",
         money: "Euro",
         color: "緑：国土、自由\n白：雪、平和\n赤：愛国、友愛"
    ),
    City(name: "japan",
         image: #imageLiteral(resourceName: "japan"),
         shortDescription: "Asia",
         description1: "Tokyo",
         language: "Japanese",
         money: "yen",
         color: "丸：太陽の光明\n白：純潔、神聖"
    ),
    City(name: "Kenya",
         image: #imageLiteral(resourceName: "Kenya"),
         shortDescription: "Africa",
         description1: "Nairobi",
         language: "English、Swahili",
         money: "shilling",
         color: "黒：国民\n赤：独立闘争で流された血\n緑：豊かな森林\n白：統一と平和"
    ),
    City(name: "korea",
         image: #imageLiteral(resourceName: "korea"),
         shortDescription: "Asia",
         description1: "Seoul",
         language: "Korean",
         money: "South Korean won",
         color: "赤と青の円：赤は陽、青は陰の意味"
    ),
    City(name: "Malaysia",
         image: #imageLiteral(resourceName: "Malaysia"),
         shortDescription: "Asia",
         description1: "Kuala Lumpur",
         language: "Malay",
         money: "Ringgit",
         color: "月と太陽：イスラム教のシンボル\n黄：スルタンの権威"
    ),
    City(name: "Mexico",
         image: #imageLiteral(resourceName: "Mexico"),
         shortDescription: "North American",
         description1: "Mexico city",
         language: "Spanish",
         money: "peso mexicano",
         color: "緑：独立\n白：カトリック教会と宗教の純粋性\n赤：民族の統一"
    ),
    City(name: "Mongolia",
         image: #imageLiteral(resourceName: "Mongolia"),
         shortDescription: "Asia",
         description1: "Ulaanbaatar",
         language: "Mongolian",
         money: "Tugrik",
         color: "赤：勝利、歓喜\n青：献身、忠誠"
    ),
    City(name: "Morocco",
         image: #imageLiteral(resourceName: "Morocco"),
         shortDescription: "Africa",
         description1: "Rabat",
         language: "Arabic",
         money: "dirham",
         color: "緑：イスラム教\n赤：モロッコ国民の祖アラウィー家を表す王家の伝統色"
    ),
    City(name: "Netherlands",
         image: #imageLiteral(resourceName: "Netherlands"),
         shortDescription: "Europe",
         description1: "Amsterdam",
         language: "Dutch",
         money: "Euro",
         color: "赤：独立戦争での国民の勇気\n白：信仰心\n青：祖国への忠誠"
    ),
    City(name: "North_Korea",
         image: #imageLiteral(resourceName: "North_Korea"),
         shortDescription: "Asia",
         description1: "Pyongyang",
         language: "Korean",
         money: "Korean won",
         color: "円：太極、宇宙\n星：社会主義\n青：平和\n白：純潔、光明\n赤：社会主義国家の建設"
    ),
    City(name: "Norway",
         image: #imageLiteral(resourceName: "Norway"),
         shortDescription: "Europe",
         description1: "Oslo",
         language: "Norwegian、Sami",
         money: "Norwegian krone",
         color: "赤・白・青：自由への願いが込められている"
    ),
    City(name: "NewZealand",
         image: #imageLiteral(resourceName: "NewZealand"),
         shortDescription: "Oceania",
         description1: "Wellington",
         language: "English、Māori..etc",
         money: "Newzealand dollar",
         color: "イギリスマーク：イギリス連邦の一員であることを表す"
    ),
    City(name: "Peru",
         image: #imageLiteral(resourceName: "Peru"),
         shortDescription: "South America",
         description1: "Lima",
         language: "Aymara、Quechua、Spanish",
         money: "nuevo sol",
         color: "赤：勇気と愛国心\n白：平和と名誉"
    ),
    City(name: "Philippines",
         image: #imageLiteral(resourceName: "Philippines"),
         shortDescription: "Asia",
         description1: "Manila",
         language: "English、Filipino",
         money: "Philippine peso",
         color: "太陽：独立と自由\n白：平和と友愛\n青：真実と正義\n赤：愛国心と勇気"
    ),
    City(name: "Poland",
         image: #imageLiteral(resourceName: "Poland"),
         shortDescription: "Europe",
         description1: "Warsaw",
         language: "Polish",
         money: "zloty",
         color: "白：白鷲、平和\n赤：赤鷲、自由"
    ),
    City(name: "Portugal",
         image: #imageLiteral(resourceName: "Portugal"),
         shortDescription: "Europe",
         description1: "Lisbon",
         language: "Portuguese、Miranda",
         money: "Euro",
         color: "緑：誠実と希望\n赤：十字革命で流された血、勝利"
    ),
    City(name: "Romania",
         image: #imageLiteral(resourceName: "Romania"),
         shortDescription: "Europe",
         description1: "Bucharest",
         language: "Romanian",
         money: "Romanian leu",
         color: "青：空\n黄：穀物、鉱物\n赤：勇気、独立闘争"
    ),
    City(name: "Russia",
         image: #imageLiteral(resourceName: "Russia"),
         shortDescription: "Eurasia",
         description1: "Moscow",
         language: "Russian",
         money: "Russian ruble",
         color: "白：高貴と率直、ベラルーシ人\n青：名誉と純潔性、ウクライナ人\n赤：愛と勇気、ロシア人"
    ),
    City(name: "SaudiArabia",
         image: #imageLiteral(resourceName: "SaudiArabia"),
         shortDescription: "Asia",
         description1: "Riyadh",
         language: "Arabic",
         money: "rial",
         color: "文字：「アッラーのほかに神はなく、ムハンマドはアッラーの使徒」\n緑：イスラム教"
    ),
    City(name: "South_Africa",
         image: #imageLiteral(resourceName: "South_Africa"),
         shortDescription: "Africa",
         description1: "Pretoria",
         language: "English..etc",
         money: "Rand",
         color: "赤：黒人解放運動で流された血\n青：空と海\n緑：農業と森林資源\n黄：鉱物資源\n黒：黒人\n白：白人"
    ),
    City(name: "Spain",
         image: #imageLiteral(resourceName: "Spain"),
         shortDescription: "Europe",
         description1: "Madrid",
         language: "Spanish",
         money: "Euro",
         color: "赤：外敵を撃退したときに流された血\n黄：豊かな国土"
    ),
    City(name: "Sweden",
         image: #imageLiteral(resourceName: "Sweden"),
         shortDescription: "Europe",
         description1: "Stockholm",
         language: "Swedish",
         money: "Norwegian Krone",
         color: "青：大空、湖\n黄：黄金に輝く太陽"
    ),
    City(name: "Switzerland",
         image: #imageLiteral(resourceName: "Switzerland"),
         shortDescription: "Europe",
         description1: "Bern",
         language: "Italian,German,French",
         money: "Swiss franc",
         color: "十字：キリスト教\n赤：主権"
    ),
    City(name: "Tailand",
         image: #imageLiteral(resourceName: "Tailand"),
         shortDescription: "Asia",
         description1: "Bangkok",
         language: "Thai",
         money: "Baht",
         color: "赤：国家と国民\n白：仏教\n青：タイ王室"
    ),
    City(name: "Turkey",
         image: #imageLiteral(resourceName: "Turkey"),
         shortDescription: "Europe",
         description1: "Ankara",
         language: "Turkish",
         money: "Turkish lira",
         color: "月と星：団結、進歩、民族の統一、国の独立\n赤：オスマン王朝の象徴"
    ),
    City(name: "Ukraine",
         image: #imageLiteral(resourceName: "Ukraine"),
         shortDescription: "Europe",
         description1: "Kiev",
         language: "Ukrainian",
         money: "Hryvnia",
         color: "青：空\n黄：小麦、農業"
    ),
    City(name: "UnitedKingdom",
         image: #imageLiteral(resourceName: "UnitedKingdom"),
         shortDescription: "Europe",
         description1: "London",
         language: "English,Irish..etc",
         money: "british pound",
         color: "連合王国を表す"
    ),
    City(name: "Vietnam",
         image: #imageLiteral(resourceName: "Vietnam"),
         shortDescription: "Asia",
         description1: "Hanoi",
         language: "Vietnamese",
         money: "Don",
         color: "星：労働者・農民・兵士・知識人・青年\n赤：社会主義の象徴・革命で流した血"
    )
  ]
}
